version: '3'
services:
  frontend:
    container_name: frontend
    image: frontend-test2
    security_opt:
      - seccomp=profile.json
    environment:
      - DISPLAY=host.docker.internal:0
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - spearmint
  backend:
    container_name: backend
    image: backend-test2
    ports:
      - "3001:3001"
    networks:
      - spearmint
networks:
  spearmint:
    driver: bridge
